---
locale: pt
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: query_outputs
  query: cat tarefas.txt
  output: |
    limpar o escritório
    fazer as compras
    terminar a lição
name: Preciso de uma substituição
