---
name: Arquivos, versões e terminais
locale: pt
type: learning
beta: false
teacher_info: ''
language: bash
id_format: "%05d"
order:
- 1
- 2
- 3
- 4
- 16
- 9
- 8
- 17
- 21
- 18
- 19
- 20
private: false
