mkdir poesias
cd poesias
mkdir drummond
mkdir lispector
mkdir machado_de_assis
touch a_hora_da_estrela.txt
touch machado_de_assis/misa_de_gallo.txt
touch drummond/Sentimento_do_mundo.txt
touch drummond/poesias.txt
touch lispector/a_descoberta_do_mundo.txt
touch lispector/laços_de_familia.txt
