---
locale: pt
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_outputs
  output: "<html>\n  <head>  \n    <title>Meu Primeiro CV</title>\n  </head>\n</html>"
name: The cat is under the terminal
