---
locale: pt
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "...hacer una copia del archivo original, y luego modificar esa copia."
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "...modificar el archivo original, y luego hacer una copia."
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "...hacer una copia del archivo, luego modificar esa copia, y finalmente
    eliminar el archivo original."
  checked: false
name: A guardar, a guardar, cada cosa en su lugar
