---
locale: pt
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: query_passes
  query: grep "Manejo de Terminal" /home/mumuki/curriculums/curriculum-v5.html
name: Juntando tudo
