---
locale: pt
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: query_outputs
  query: cat tareas.txt
  output: |-
    limpiar el taller
    hacer las compras
    terminar lección
name: Necesito un reemplazo
