---
locale: pt
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: query_passes
  query: test -e /home/mumuki/rock/la_vida_es_una_moneda.mp3 && test ! -e /home/mumuki/rock/la_bida_es_una_moneda.mp3
name: "¡A moverse!"
