---
locale: pt
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "...fazer uma cópia do arquivo original e modificar essa cópia."
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "...modificar o arquivo original e em seguida fazer uma cópia."
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "...fazer uma cópia do arquivo, modificar a cópia e, finalmente, excluir
    o arquivo original."
  checked: false
name: Salvando, salvando
